### ISSUE TITLE
fix puppet validate

### ISSUE THREAD

**Issue by jordiprats** [NTTCom-MS/eyp-tomcat#20]
1.19s$ bundle exec rake validate

ruby -c lib/facter/eyp_tomcat_check_jdk.rb

Syntax OK

ruby -c lib/facter/eyp_tomcat_check_java.rb

Syntax OK

---> syntax:manifests

Illegal parameter name. The given name 'WatchedResource' does not conform to the naming rule /^[a-z_]\w*$/ at /home/travis/build/jordiprats/eyp-tomcat/manifests/context.pp:3:29

Illegal parameter name. The given name 'Manager' does not conform to the naming rule /^[a-z_]\w*$/ at /home/travis/build/jordiprats/eyp-tomcat/manifests/context.pp:4:29

Found 2 errors. Giving up

Could not parse for environment _root_: Syntax error at '[' at /home/travis/build/jordiprats/eyp-tomcat/manifests/instance.pp:238:23

rake aborted!

/usr/local/rvm/gems/ruby-2.2.3/gems/puppet-syntax-2.1.0/lib/puppet-syntax/tasks/puppet-syntax.rb:47:in `block (2 levels) in initialize'

/usr/local/rvm/gems/ruby-2.2.3/gems/puppetlabs_spec_helper-1.0.1/lib/puppetlabs_spec_helper/rake_tasks.rb:257:in `block in <top (required)>'

/usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'

/usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'

Tasks: TOP => syntax => syntax:manifests

(See full trace by running task with --trace)

**Comment by jordiprats** [comment]
already fixed
